version: "3.8"
services:
  node-webserver:
    container_name: "web-server"
    build: "./"
    ports:
      - "3000:3000"
    
    depends_on: 
      - db

  db:
    image: "postgres:12"
    restart: on-failure
    environment: 
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=Website
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  postgres:
        