version: "3.8"
services:
  node-webserver:
    container_name: "web-server"
    build: "./"
    ports:
      - "3000:3000"
    
    depends_on: 
      - db

  db:
    image: "postgres:12"
    restart: on-failure
    # https://github.com/docker-library/postgres/issues/435
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=Website
    volumes:
      - ./postgres_data:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
        